---
services:
  backup_for_my_service:
    driver:
      name: DriverLocal
      config:
        path: ./test_data/backup_for_my_service/*.sql.gz

  backup_for_my_other_service:
    driver:
      name: DriverLocal
      config:
        path: ./test_data/backup_for_my_other_service/*.tar.bz2
