version: '3.6'
services:
  pfe:
    image: pfe:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/opt/exporter/config.yml:ro
    env_file:
      - env/pfe.env
