{
 "title": "Prometheus File Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  { "title": "Global - services = $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 21, "w": 12, "x": 0, "y": 1 } },
  {
   "title": "Last backup filesize",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "file_stat_last_file_size{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "file_stat_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "file_stat_count{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "file_stat_last_modification_time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "file_stat_last_modification_time{service=~\"$service\"}*1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Stats for $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "file_stat_count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "file_stat_count{service=\"$service\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "file_stat_last_file_size",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 3, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "file_stat_last_file_size{service=\"$service\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "file_stat_last_modification_time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 7, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "file_stat_last_modification_time{service=\"$service\"}*1000",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  }
 ]
}